(function(){
'use strict';
const M=window.SystemOverviewModel,$=s=>document.querySelector(s),lab=$('[data-system-lab]');if(!lab)return;lab.hidden=false;
let mode='service',step=0,timer=null;const reduced=matchMedia('(prefers-reduced-motion:reduce)');
const nodes={service:[['client','客户端','',150,22],['front','HTTP / Tokenizer','入口进程',150,116],['scheduler','Scheduler','调度进程',80,250],['detokenizer','Detokenizer','反分词进程',220,250]],inside:[['scheduler','Scheduler','选择本轮工作',150,95],['runner','Worker / Runner','执行与采样职责',80,215],['cache','缓存 / 分配器','索引、保护与位置',220,215],['gpu','GPU 模型与 KV','设备资源，非新进程',150,312]]};
function linkList(keys){return keys.map(key=>`<a href="${M.modules[key][1]}">${M.modules[key][0]} ↗</a>`).join('');}
function drawFlow(){const d=M.frame(mode,step),h=380,list=mode==='inside'?M.inside:M.service,unique=[...new Set(list.map(x=>x.path))];
 $('#system-scene').innerHTML=`<h3>${d.title}</h3><div class="system-map ${mode}"><div class="system-boundary"><small>${mode==='service'?'一个服务实例 · 本页普通路径':'同一 Scheduler 进程协调'}</small></div><svg class="system-wires" viewBox="0 0 300 ${h}" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="system-arrow" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0 L6 3 L0 6 Z"/></marker></defs>${unique.map(path=>`<path d="${path}" class="${path===d.path?'active':''}" ${path===d.path?'marker-end="url(#system-arrow)"':''}/>`).join('')}${!reduced.matches?`<circle r="3"><animateMotion dur="1.7s" repeatCount="indefinite" path="${d.path}"/></circle>`:''}</svg>${nodes[mode].map(([id,name,note,x,y])=>`<div class="system-node ${id} ${[d.from,d.to].includes(id)?'active':''}" data-role="${id}" style="left:${x/3}%;top:${y/h*100}%"><strong>${name}</strong>${note?`<small>${note}</small>`:''}</div>`).join('')}<span class="system-payload" style="left:${d.x/3}%;top:${d.y/h*100}%">${d.payload}</span></div><p class="system-status">${mode==='inside'?`已写 KV ${d.kv} 个位置 · 已采样 ${d.sampled} 个 token`:`已采样 ${d.sampled} 个 · 本图客户端可见 ${d.visible} 个`}</p>`;
 return {...d,why:mode==='service'?'普通 Python HTTP、单 tokenizer、单卡合并部署，无 overlap。本图展示首段输出的一次依赖链，不规定后续计算与网络回程必须串行。Token 标签是教学设定；CPU 对象、设备内存与网络包不是同一层对象。':'这是职责与资源图，四个框不能数成四个进程。模型层的 K/V 位于设备 buffer，由主机对象管理；缓存索引和分配器不计算 Transformer。选定一次可接纳的 Prefill，没有模拟不足、取消和特殊模型；这些分支在相应课程里展开。'};
}
function drawTopology(){const kind=$('#system-topology').value,d=M.topology(kind),labels=kind==='tp'?['TP rank 0','TP rank 1']:kind==='dp'?['DP 副本 0','DP 副本 1']:['Prefill 实例','Decode 实例'];
 $('#system-scene').innerHTML=`<h3>${kind==='tp'?'两张卡共同完成一个模型副本':kind==='dp'?'两个副本分别处理请求':'两个角色接力处理同一请求'}</h3><div class="system-topology ${kind}"><small>${kind==='tp'?'一个副本 · TP=2':kind==='dp'?'DP 服务入口 · 两个独立执行副本':'两个服务角色 · 各自覆盖完整模型'}</small><div class="system-devices">${[0,1].map((rank)=>`${rank?`<div class="system-between"><small>${kind==='tp'?'协作':kind==='dp'?'':'KV'}</small>${kind==='tp'?'↔':kind==='dp'?'·':'→'}</div>`:''}<div class="system-device ${rank?'right':''}"><strong>${labels[rank]}</strong><small>${kind==='tp'?'各层代表矩阵分片':'各层完整覆盖'}</small><div class="system-weights">${d.layers.map(layer=>`<div class="system-weight"><i style="width:${d.fractions[rank]*100}%"></i><span>L${layer}</span></div>`).join('')}</div><div class="system-route">${d.assignments[rank].join('')}</div></div>`).join('')}</div></div><p class="system-note">${kind==='tp'?'图中半块仅示意可切分矩阵；不是所有参数都减半。':kind==='dp'?'本例按 round-robin 分派；每个请求只送一个副本。':'箭头概括 KV 与请求状态交接；可用与释放仍有门槛。'}</p>`;
 return {source:d.source,links:d.links,caption:kind==='tp'?'TP 按同层内的计算与参数切分协作。各 rank 有自己的调度执行参与者；它们共同完成同一副本的工作。':kind==='dp'?'DP 给不同请求分配不同副本，各副本分别调度并持有本地状态。共享服务入口，不等于共享一份 KV。':'PD 按 Prefill / Decode 阶段分工。两侧都要覆盖整套模型，不能理解为 P 跑前半层、D 跑后半层。',why:'三张拓扑分别选取 TP=2、DP=2 且每副本 TP=1、P/D 各单卡的独立教学配置。DP 采用当前 Python controller 的轮询路径，排除显式外部分派与异常副本。图只画三层代表权重；真实层数、TP 复制参数和通信方式由模型与配置决定。PD 的首 token 与元数据也属于交接，详细条件见通信和分离部署课程。这不是可以任意叠加的兼容性保证。'};
}
function render(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));document.querySelectorAll('[data-settings]').forEach(e=>e.hidden=e.dataset.settings!==mode);$('#system-controls').hidden=mode==='topology';$('#system-scene').dataset.mode=mode;$('#system-scene').dataset.step=step;const d=mode==='topology'?drawTopology():drawFlow();$('#system-caption').textContent=d.caption;$('#system-why').textContent=d.why;const [file,line]=M.sources[d.source];$('#system-source').href=`https://github.com/sgl-project/sglang/blob/${M.revision}/${file}#L${line}`;$('#system-related').innerHTML=linkList(d.links);$('#system-status').textContent=`${step+1} / 6`;$('#system-previous').disabled=step===0;$('#system-next').disabled=step===5;}
function stop(){clearInterval(timer);timer=null;$('#system-play').textContent='播放';$('#system-play').setAttribute('aria-pressed','false');}function reset(){stop();step=0;render();}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;reset();});$('#system-topology').onchange=reset;$('#system-next').onclick=()=>{stop();step=Math.min(5,step+1);render();};$('#system-previous').onclick=()=>{stop();step=Math.max(0,step-1);render();};$('#system-reset').onclick=reset;$('#system-play').onclick=()=>{if(timer){stop();return;}if(step===5)step=0;$('#system-play').textContent='暂停';$('#system-play').setAttribute('aria-pressed','true');render();timer=setInterval(()=>{step++;render();if(step===5)stop();},2800);};reduced.addEventListener('change',render);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});render();
})();
