(()=>{'use strict';const M=window.PerformanceModel,$=s=>document.querySelector(s),lab=$('[data-performance-lab]');if(!M||!lab)return;
let mode='clock',step=0,timer=null;const scene=$('#perf-scene'),fmt=n=>Number.isInteger(n)?String(n):n.toFixed(1),value=id=>$(id).value;
const stat=(label,n,unit='ms',empty='待观测')=>`<div class="perf-stat">${label}<strong>${n===null?empty:fmt(n)+' '+unit}</strong></div>`;
const url=key=>{const [file,line]=M.sources[key];return `https://github.com/sgl-project/sglang/blob/${M.revision}/${file}#L${line}`;};
function last(){return mode==='clock'?7:mode==='packet'?M.packets(value('#packet-kind')).chunks.length+1:mode==='experiment'?3:2;}
function stop(){clearInterval(timer);timer=null;$('#perf-play').textContent='播放';$('#perf-play').setAttribute('aria-pressed','false');}
function render(){
 let html='',caption='',why='',source='metrics';
 if(mode==='clock'){
 const d=M.timeline(value('#clock-kind')),now=step?d.segments[step-1].end:0;
 html=`<h3>一条请求 · 当前 ${now} ms</h3><div class="perf-timeline"><div class="perf-track">${d.segments.map((s,i)=>`<div class="perf-stage ${s.kind} ${i>=step?'future':''} ${i===step-1?'current':''}" style="height:${s.duration}px"><span>${s.label}</span><b>${s.duration} ms</b></div>`).join('')}</div><div class="perf-ruler">${[[0,'就绪'],[d.send,'发出'],[d.first,'首包'],[d.end,'结束']].map(([t,label])=>`<div class="perf-mark" style="top:${t}px">${t}<br>${label}</div>`).join('')}</div></div><div class="perf-stats">${stat('客户端 TTFT',step>=5?d.ttft:null)}${stat('HTTP E2E',step>=7?d.e2e:null)}${stat('就绪到结束',step>=7?d.total:null)}</div>`;
 const texts=['请求已就绪，先等待客户端的并发许可。','取得许可，才进入请求适配器并开启单请求秒表。','请求进入服务；接下来要等 Scheduler 给出执行机会。','轮到这条请求，才开始处理尚未缓存的输入。','Prefill 完成并采样首 token；客户端尚未收到它。','首包到达客户端，TTFT 在这里截断；后续仍需生成。','后续 token 到齐，流结束消息仍可能晚一些到达。','最后的流数据到达，HTTP 延迟才结束。客户端许可等待仍在这个区间之外。'];
 caption=texts[step];why='这条串行时间线为教学分解，不能从一个 TTFT 数字反推所有段。真实服务可能有重叠、分块和多级排队；需关联请求日志与 Trace。单请求秒表在 adapter 内开始，外层 semaphore 等待未计入；服务端 TTFT 使用另一套 time_stats，不能直接相减。';source=step<2?'permit':'adapter';
 }else if(mode==='packet'){
 const d=M.packets(value('#packet-kind'));let prev=0;
 html='<h3>客户端收到的是数据包</h3><div class="perf-packets">'+d.chunks.map((c,i)=>{const count=c.n-prev,begin=prev;prev=c.n;return `${i?`<div class="perf-gap ${step<=i?'perf-hidden':''}">${c.t-d.chunks[i-1].t} ms / ${count} token${count>1?' → 均摊 40 ms':''}</div>`:''}<div class="perf-packet ${step<=i?'perf-hidden':''}"><time>${c.t} ms</time><div class="perf-tokens">${Array.from({length:count},(_,j)=>`<span class="perf-token">${begin+j+1}</span>`).join('')}</div></div>`;}).join('')+`<div class="perf-gap ${step<last()?'perf-hidden':''}">+ 20 ms 尾部 → ${d.end} ms 结束</div></div><div class="perf-stats">${stat('TTFT',step?d.ttft:null)}${stat('请求 TPOT',step===last()?d.tpot:null,'ms',step===last()?'无样本':'待观测')}${stat('ITL 样本',step===last()?d.itls.length:null,'个')}</div>`;
 caption=step===0?'先记录首个有内容的数据包，再记录后续包的到达间隔。':step===last()?d.n===1?'只产生一个 token，没有后续 token 区间；TPOT 应理解为缺少样本。':`TPOT = (${d.end} − 100) / (${d.n} − 1) = ${fmt(d.tpot)} ms；它包含这里的 20 ms 尾部。`:value('#packet-kind')==='bundle'&&step===2?'第二包一次带来 3 个 token。工具把 120 ms 均摊成三个 40 ms；这不证明设备每 40 ms 产生一次 token。':'带编号的方块表示本次包新增的 token；包到达时间才是客户端直接观测。';
 why='固定 native /generate 适配器只在非空 text 时更新首包/后续包计时。completion_tokens 的增量大于 1 时，将包间隔均摊到新增 token；首包内部 token 的生成间隔没有被观测。calculate_metrics 只对 output_len > 1 的成功请求记录 TPOT；多请求均值按请求等权，ITL 则按记录的样本加权。其他协议需分别核对适配器。';source='chunks';
 }else if(mode==='experiment'){
 const kind=value('#experiment-kind'),{a,b}=M.experiment(kind),max=a.wall;
 const run=(d,name,shown)=>`<div class="perf-run ${shown?'':'perf-hidden'}"><div class="perf-run-head"><strong>${name}</strong><span>${d.wall} ms 完成 24 token</span></div><div class="perf-run-axis">${d.groups.map(g=>`<div class="perf-batch" style="left:${g.start/max*100}%;width:${(g.end-g.start)/max*100}%"><i style="width:${d.first/d.e2e*100}%"></i><span>${g.ids.length===1?'R'+g.ids[0]:`R${g.ids[0]}–${g.ids.at(-1)}`}</span></div>`).join('')}</div></div>`;
 html='<h3>相同 6 条请求，每条输出 4 token</h3>'+run(a,kind==='prefill'?'A · 原 Prefill':'A · 并发许可 1',step>=1)+run(b,kind==='prefill'?'B · 只把 Prefill 耗时减半':'B · 并发许可 3',step>=2)+`<p class="perf-hint">同一时间比例 · 色深部分为 Prefill · 外部就绪时刻均为 0</p><div class="perf-measures ${step<3?'perf-hidden':''}">${[a,b].map((d,i)=>`<div><strong>${i?'B':'A'}</strong><p>输出吞吐 ${fmt(d.throughput)} token/s</p><p>HTTP E2E ${fmt(d.e2e)} ms</p><p>就绪到完成均值 ${fmt(d.readyMean)} ms</p></div>`).join('')}</div>`;
 caption=['先固定请求集合、输出长度和计时定义。切换实验时，每组 A/B 只改变一个输入。','A 的每一块是一轮执行；后续组等前一组释放许可。','B 仍要遵守相同依赖，改变一个条件后重新计算完成时刻。',kind==='prefill'?'Prefill 耗时减半，但 Decode 未变：总时长 360 → 270 ms，吞吐提升 1.33 倍，不是 2 倍。':'更多请求一起执行，24 token 更早完成；本例单请求 HTTP E2E 却从 120 增到 180 ms。许可前等待减少，和许可后的执行变慢可以同时发生。'][step];
 why='整理者构造的封闭批次模型：6 条请求同时就绪，取得许可后立即发出，按组同步完成，无网络尾部；每请求固定输出 4 token。并发 1 的 Prefill/Decode 总耗时为 60/60 ms，并发 3 为 90/90 ms，表示预设的共享成本，不是 SGLang 性能预测。吞吐分母为这批工作完成时间；真实 serving benchmark 还可能计入发压节奏、收尾查询与 profiler 停止。真实 A/B 还要固定模型、硬件、输入长度、缓存、采样、版本，并重复采集分布。';source=kind==='prefill'?'window':'throughput';
 }else{
 const d=M.sample(value('#sample-kind'));
 html='<h3>同一组 4 条请求 · 固定观察 1 秒</h3><div class="perf-sample">'+d.requests.map((r,i)=>`<div class="perf-request ${!r.success&&step===2?'failed':''} ${step===0||(step===1&&i===3)?'perf-hidden':''}"><span class="perf-dot">R${r.id}</span><small>${step===0?'待观测':i===3&&step===1?'仍等待':!r.success?'失败 · 排除':r.ttft+' ms'}</small></div>`).join('')+`</div><div class="perf-stats ${step<2?'perf-hidden':''}">${stat('成功请求平均 TTFT',d.mean)}${stat('成功请求 P95',d.p95)}${stat('失败',d.failed,'/ 4')}</div><p class="perf-hint ${step<2?'perf-hidden':''}">成功输出吞吐 ${d.throughput} token/s · 失败请求的部分输出不计入</p>`;
 caption=['四条请求都进入观察集合，尚未知道谁能成功。','R1–R3 已成功；R4 仍在等待。此刻不能把前三条的均值当作整组结果。',d.failed?'R4 失败后被移出成功延迟分布。均值从 185 降到 80 ms，同时失败率升到 25%；这不是服务更快的证据。':'R4 最终成功，500 ms 的首包等待进入统计；较慢的请求没有被藏起来。'][step];
 why='calculate_metrics 只将 success=True 的延迟、输入和输出计入对应汇总。这里假设每条成功请求输出 4 token，固定 1 秒观察窗口；R4 的失败发生在窗口内。P95 采用线性插值，与固定实现的 NumPy 默认计算一致。四个样本只用于演示筛选效应，不足以估计生产尾延迟。全失败时更不能把“没有成功延迟样本”解释成 0 ms。';source='success';
 }
 scene.innerHTML=html;scene.dataset.mode=mode;scene.dataset.step=step;$('#perf-caption').textContent=caption;$('#perf-why').textContent=why;$('#perf-source').href=url(source);$('#perf-status').textContent=`${step+1} / ${last()+1}`;$('#perf-previous').disabled=step===0;$('#perf-next').disabled=step===last();if(step===last())stop();
}
function reset(){stop();step=0;render();}
lab.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;lab.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));lab.querySelectorAll('[data-settings]').forEach(x=>x.hidden=x.dataset.settings!==mode);$('.parallel-details').open=false;reset();}));
lab.querySelectorAll('select').forEach(s=>s.addEventListener('change',reset));$('#perf-next').addEventListener('click',()=>{stop();step=Math.min(last(),step+1);render();});$('#perf-previous').addEventListener('click',()=>{stop();step=Math.max(0,step-1);render();});$('#perf-reset').addEventListener('click',reset);$('#perf-play').addEventListener('click',()=>{if(timer)return stop();if(step===last())step=0;$('#perf-play').textContent='暂停';$('#perf-play').setAttribute('aria-pressed','true');render();timer=setInterval(()=>{step++;render();},2400);});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});lab.hidden=false;render();
})();
