(function(){
'use strict';
const M=window.SchedulingModel,$=s=>document.querySelector(s),lab=$('[data-schedule-lab]');if(!lab)return;lab.hidden=false;
let mode='admission',step=0,timer=null,last=0;
const req=id=>M.requests.find(r=>r.id===id),chip=id=>`<span class="schedule-chip ${id}">${id}</span>`;
function drawAdmission(){const events=M.admission($('#schedule-policy').value,$('#admission-case').value),d=events[step];last=events.length-1;const r=d.current?req(d.current):null,kind=d.config.resource,need=r?(kind==='input'?r.input-r.hit:kind==='kv'?r.input-r.hit+r.maxNew+1:1):0,cap=d.config[kind==='input'?'input':kind==='kv'?'kv':'rows'];
 const amounts=d.admitted.map(id=>({id,n:kind==='input'?req(id).input-req(id).hit:kind==='kv'?req(id).input-req(id).hit+req(id).maxNew+1:1}));if(kind==='kv'&&d.protectedTokens+d.trial)amounts.push({id:'pin',n:d.protectedTokens+d.trial});const used=amounts.reduce((n,x)=>n+x.n,0),scale=Math.max(cap,used),available=cap-used;
 const titles={waiting:'先看三条等待请求',sorted:'排序只改变尝试顺序',check:`检查 ${d.current} 能否加入`,commit:`${d.current} 已加入本轮计划`,blocked:`${d.current} 留在等待队列`,stop:'额度用完，停止继续追加',ready:'本轮计划与剩余等待'};
 const unit=kind==='rows'?'行':'token',name=kind==='input'?'本轮输入额度':kind==='kv'?'KV 准入预算':'可用请求行';
 $('#schedule-scene').innerHTML=`<h3>${titles[d.kind]}</h3><p class="schedule-note">等待顺序 · 命中前缀已在 GPU</p><div class="schedule-queue">${d.waiting.map(id=>{const x=req(id);return `<div class="schedule-request ${id} ${id===d.current?'current':''}" data-request="${id}"><strong>${id}</strong><small>${x.hit?`命中 ${x.hit} · `:''}待算 ${x.input-x.hit}</small></div>`;}).join('')||'<span class="schedule-empty">等待队列为空</span>'}</div><div class="schedule-arrow" aria-hidden="true">↓</div><div class="schedule-gate ${d.kind==='blocked'?'blocked':''}" data-resource="${kind}"><div><strong>${name}</strong><span>${d.kind==='check'?`${d.current} 需要 ${need} ${unit}`:`余 ${available} / ${cap} ${unit}`}</span></div><div class="schedule-bar">${amounts.map(x=>`<i class="${x.id}" style="width:${x.n/scale*100}%"></i>`).join('')}${used>cap?`<b style="left:${cap/scale*100}%"></b>`:''}</div><small>${kind==='kv'?`实色为本轮预留，斜线为受保护前缀；余额 ${available}。`:`已列入计划 ${used} ${unit}${used>cap?'；虚线标记原额度':''}。`}</small></div><div class="schedule-arrow" aria-hidden="true">↓</div><div class="schedule-batch"><small>本轮候选 batch · 尚未执行</small>${d.admitted.map(chip).join('')||'<span class="schedule-empty">尚未接纳</span>'}</div>`;
 let caption='',source='policy';
 if(d.kind==='waiting')caption='R1 先到，R2 有 4 个可复用前缀，R3 输入较短。先分清匹配、排序与真正接纳。';
 if(d.kind==='sorted'){caption=$('#schedule-policy').value==='fcfs'?'FCFS 保留等待顺序；排第一仍需通过准入检查。':'LPM 先尝试命中更长的 R2；它没有承诺最短等待或最高吞吐。';source=$('#schedule-policy').value==='fcfs'?'policy':'lpm';}
 if(d.kind==='check'){caption=kind==='kv'?`先保护 ${d.current} 的命中前缀，再看实时余额 ${d.available}。本次需求 ${need} 必须严格小于余额。`:kind==='rows'?`先检查请求行能否容纳 ${d.current}，再检查 token 预算。`:`${d.current} 要算 ${r.input-r.hit} 个新位置。未分块路径允许首条超过输入额度；后续候选有追加门槛。`;source=kind==='kv'?'pin':kind==='rows'?'rows':'input';}
 if(d.kind==='commit'){caption=`${d.current} 进入计划，额度随之扣除。接纳不等于已经分配全部 KV 或完成一次 forward。`;source='commit';}
 if(d.kind==='blocked'){caption=d.reason==='kv'?`${d.current} 需求 ${r.input-r.hit+r.maxNew+1}，检查时余额 ${d.checkAvailable}，无法接纳；临时保护已退回。`:d.reason==='rows'?'可用请求行已用完，本轮不再接纳新的请求。':`${d.current} 的新输入不少于剩余额度，停止追加。排在后面的短请求也不会在本轮越过它。`;source=d.reason==='kv'?'budget':d.reason==='rows'?'rows':'input';}
 if(d.kind==='stop'){caption='Adder 返回 OTHER，意思是停止继续追加。刚刚加入计划的请求仍然会被执行，不能把 OTHER 直接理解为接纳失败。';source='stop';}
 if(d.kind==='ready'){caption=`本轮接纳 ${d.admitted.join('、')||'无'}；${d.waiting.length?d.waiting.join('、')+' 继续等待。':'等待请求已全部进入计划。'}后续再分配与执行。`;source='commit';}
 return {caption,source,why:'本例 page_size=1、普通 RadixCache / 固定 token 池，无 chunk、优先级、HiCache 或特殊模型。R2 的 4-token 前缀初始可驱逐；保护它会减少实时可用加可驱逐容量。新请求 KV 检查量 = 未命中输入 + 剩余输出上限 2 + 1；使用严格 <。本轮输入额度不包含缓存命中。无 chunk 时首条可超过输入额度；后续新输入 >= 剩余额度就停止。这是准入账本，不是已分配 KV 图。其他预算保持宽裕，页与模型特例见完整笔记。'};
}
function drawChunks(){const events=M.chunks(Number($('#chunk-cap').value)),d=events[step];last=events.length-1;const rows=d.kind==='plan'?[...d.history,d.plan]:d.history;
 $('#schedule-scene').innerHTML=`<h3>${d.kind==='waiting'?'L 已开始，S 仍在等待':d.kind==='plan'?`为第 ${d.round} 轮选择工作`:`第 ${d.round} 轮完成 Prefill 工作`}</h3><div class="schedule-progress"><div class="schedule-work-row"><span>L 剩 ${d.left} 个</span><div class="schedule-work">${Array.from({length:10},(_,i)=>`<i class="${i>=d.left?'done':''}"></i>`).join('')}</div></div><div class="schedule-work-row short"><span>S 剩 ${d.shortLeft} 个</span><div class="schedule-work">${[0,1].map(i=>`<i class="${i>=d.shortLeft?'done':''}"></i>`).join('')}</div></div></div><div class="schedule-arrow" aria-hidden="true">↓</div>${rows.map((p,i)=>`<div class="schedule-round ${d.kind==='plan'&&i===rows.length-1?'plan':''}"><small>第 ${p.round} 轮 · ${d.kind==='plan'&&i===rows.length-1?'计划':'已执行'}</small><div class="schedule-tokens" style="--columns:${d.cap}">${Array.from({length:d.cap},(_,j)=>`<span class="schedule-token ${j<p.l?'':j<p.l+p.s?'R2':'empty'}">${j<p.l?'L':j<p.l+p.s?'S':'·'}</span>`).join('')}</div></div>`).join('')||'<p class="schedule-note">先处理已有 chunk，再尝试等待请求</p>'}<p class="schedule-note">每轮最多 ${d.cap} 个新位置 · 不含 Decode / mixed</p>`;
 const caption=d.kind==='waiting'?'L 的 Prefill 已分块开始，还剩 10 个位置；短请求 S 只需 2 个位置，但仍要等待本轮剩余额度。':d.plan.s?'L 的最后一块没有用完额度，剩余位置让 S 在同轮加入。':d.kind==='plan'?'Scheduler 先续算已有的 L，再检查等待队列。本轮额度被 L 用满，S 继续等待。':'这一轮推进了 L 的历史；只缩小 chunk，不会自动让 S 在下一轮抢到 L 前面。';
 return {caption,source:d.kind==='waiting'?'chunkFirst':'chunk',why:'普通 page_size=1，chunk 与输入额度相同，KV / 请求行预算充足，无 mixed、动态 chunk、tile cap 或其他门槛。L 是已经存在的 chunked_req，不是每轮与 S 重新按长短排序。方格表示 Prefill 新位置数，不是耗时；不能由轮次数推断真实 TTFT、公平性或吞吐。'};
}
function drawRetraction(){const d=M.retraction($('#retract-case').value,step);last=d.last;let titles,captions,keys;
 if(d.scenario==='cache'){titles=['两个请求都需要下一步容量','先驱逐可回收缓存','容量检查通过','继续本轮 Decode'];captions=['当前没有空闲槽，但有 2 个可驱逐缓存位置。先尝试回收，再决定是否回撤。','可驱逐缓存归还 2 个槽，刚好满足两个请求各增加 1 个 KV 的需求。','可用容量已足够，R1、R2 都留在运行集合，不进入回撤路径。','两条请求各推进一步；此处停在结果产生处，结束判断与释放随后处理。'];keys=['decode','check','check','decode'];}
 else {titles=['下一步 Decode 还需要 2 个槽','没有可驱逐空间','回撤 R2，释放其 KV','R2 尝试回队','R1 继续 Decode','R1 结束并保留缓存','R2 重新 Prefill','R2 追加新的输出'];captions=['R1 持有 8 个 KV，R2 持有 4 个，池内已满。两条请求下一步各需 1 个位置。','先尝试驱逐，仍没有足够空位。调度器才进入回撤，不能把这种检查直接等同于 GPU OOM。','length 策略优先保留输出较多的 R1。R2 释放 4 个 KV 与请求行，但已生成的 a 保留下来。',d.scenario==='full'?'等待队列已满，R2 在回队时被终止。完成资源释放并不保证能够恢复。':'R2 回到 waiting，重新经过准入。R1 现在有足够空间继续，R2 还不能执行。','R1 使用 1 个新槽继续计算，得到第三个输出；R2 的文本历史没有被改写。','本例 R1 已达到停止条件，9 个 KV 留在可驱逐缓存；这与空闲槽仍有区别。','后续额度足够。驱逐 R1 缓存，R2 重新分配位置，用原输入 4 个 + 已有输出 a 共 5 个 token 重建 KV。','重算历史后才得到 b，并追加到 a 后面。a 没再次计为新生成 token。'];keys=['decode','check','release',d.scenario==='full'?'full':'queue','decode','finish','reset','reset'];}
 const running=[];if(d.r1)running.push('R1');if(d.row)running.push('R2');const right=d.location==='waiting'||d.location==='released'||d.location==='aborted';
 const cells=[...Array(d.r1).fill('R1'),...Array(d.r2).fill('R2'),...Array(d.cache).fill('cache'),...Array(d.free).fill('empty')];
 $('#schedule-scene').innerHTML=`<h3>${titles[step]}</h3><div class="schedule-zones"><div class="schedule-zone"><small>${d.location==='prefill'?'重新 Prefill':'运行集合'}</small>${running.map(chip).join('')||'<span class="schedule-empty">空</span>'}</div><b aria-hidden="true">${right?'→':d.location==='prefill'?'←':'·'}</b><div class="schedule-zone ${d.location==='aborted'?'abort':''}"><small>${d.location==='aborted'?'已终止':d.location==='released'?'释放后，待回队':'等待队列'}</small>${right?chip('R2'):'<span class="schedule-empty">R2 不在此处</span>'}</div></div><div class="schedule-pool"><small>池内位置 · 空闲 ${d.free} / ${d.capacity}${d.cache?` · 斜线：可驱逐缓存 ${d.cache}`:''}</small><div class="schedule-tokens" style="--columns:7">${cells.map(id=>`<span class="schedule-token ${id==='R1'?'':id}" data-owner="${id}">${id==='cache'?'缓存':id==='empty'?'·':id}</span>`).join('')}</div></div><div class="schedule-output"><small>R2 已生成文本 · KV 清理不会删除它</small>${d.output.map((t,i)=>`<span class="${i?'new':''}">${t}</span>`).join('')}</div>`;
 return {caption:captions[step],source:keys[step],why:'普通文本、page_size=1、无共享前缀、非投机与非 Overlap。R1 原输入 7、已有输出 2、已提交 KV 8；R2 原输入 4、已有输出 1、KV 4。最后采样 token 尚无自己的 KV。默认 length 回撤顺序先保留输出较多者；本例只回撤 R2。回队成功分支另假设 R1 结束、后续准入足够，且 R1 缓存为单个可驱逐叶。回队失败展示无优先级时的队列上限；真实代码还处理最后一条仍放不下等终止分支。'};
}
function render(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));document.querySelectorAll('[data-settings]').forEach(e=>e.hidden=e.dataset.settings!==mode);$('#schedule-scene').dataset.mode=mode;$('#schedule-scene').dataset.step=step;const d=mode==='admission'?drawAdmission():mode==='chunk'?drawChunks():drawRetraction();$('#schedule-caption').textContent=d.caption;$('#schedule-why').textContent=d.why;const [file,line]=M.sources[d.source];$('#schedule-source').href=`https://github.com/sgl-project/sglang/blob/${M.revision}/${file}#L${line}`;$('#schedule-status').textContent=`${step+1} / ${last+1}`;$('#schedule-previous').disabled=step===0;$('#schedule-next').disabled=step===last;}
function stop(){clearInterval(timer);timer=null;$('#schedule-play').textContent='播放';$('#schedule-play').setAttribute('aria-pressed','false');}function reset(){stop();step=0;render();}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;reset();});document.querySelectorAll('.schedule-lab select').forEach(e=>e.onchange=reset);$('#schedule-next').onclick=()=>{stop();step=Math.min(step+1,last);render();};$('#schedule-previous').onclick=()=>{stop();step=Math.max(step-1,0);render();};$('#schedule-reset').onclick=reset;$('#schedule-play').onclick=()=>{if(timer){stop();return;}if(step===last)step=0;$('#schedule-play').textContent='暂停';$('#schedule-play').setAttribute('aria-pressed','true');render();timer=setInterval(()=>{step++;render();if(step===last)stop();},2800);};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});render();
})();
