(function(){
'use strict';
const M=window.KVMemoryModel,$=s=>document.querySelector(s),lab=$('[data-memory-lab]');if(!lab)return;lab.hidden=false;
let mode='extend',step=0,timer=null;const last={extend:4,prefix:3,sharing:6};
const labels={extend:['已有 6 个 KV 位置','分配器预留本轮写位置','模型续写原来的尾页','模型写入新页','按逻辑位置找到 KV'],prefix:['缓存与新请求','比较 token 前缀','按整页和身份判定','复用已有 KV 地址'],sharing:['前缀留在缓存','R1 命中并持有','R2 共享同一前缀','R1 结束','尝试驱逐共享页','R2 结束','驱逐缓存页']};
function cells(values){return '<div class="memory-cells">'+values.map(c=>`<div class="memory-cell ${c.state||''} ${c.focus?'focus':''}" ${c.slot!==undefined?`data-slot="${c.slot}"`:''}>${c.label??(c.p<0?'·':'p'+c.p)}${c.slot!==undefined?`<small>槽 ${c.slot}</small>`:''}</div>`).join('')+'</div>';}
function drawExtend(){const d=M.extend(Number($('#extend-length').value),step),selected=d.focused===null?(step===0?'尾页还留着 2 个位置':step===1?'本轮先用尾页 2 个位置':'原来的尾页已写满'):`逻辑 p${d.focused} → 物理槽 ${d.mapping[d.focused]}`;
 $('#memory-scene').innerHTML=`<h3>${labels.extend[step]}</h3><div class="memory-focus"><b>R1</b><span>${selected}</span></div>`+d.pages.map(p=>`<div class="memory-page ${p.free?'free':''}" data-page-id="${p.id}"><small><span>物理页 ${p.id}</span><span>${p.free?'空闲整页':p.id===7?'请求持有的尾页':'R1 持有'}</span></small>${cells(p.cells)}</div>`).join('')+`<div class="memory-legend"><span class="written">已写入</span><span class="reserved">待写入</span><span>未使用</span></div><p class="memory-count">已写 ${d.written} 个位置 · 持有 ${d.ownedPages} 页</p>`;
 const captions=['逻辑 p0 到 p5 连在一起，物理地址却落在页 1 与页 7。页 7 剩余位置仍由 R1 持有。',`本轮扩到 ${d.target} 个位置，只需新领 ${d.newPages} 页。分配器给出地址，此时还没有新 KV 值。`,'p6、p7 先利用同一请求的尾页空间，无需再领整页。',d.newPages?'剩余位置写进页 3。逻辑位置继续增加，物理页号可以跳跃。':'尾页刚好写满，本轮不需要页 3。',`请求映射把 p${d.focused} 指向槽 ${d.mapping[d.focused]}；同一槽号在各模型层对应各自的 K/V。`];
 return {caption:captions[step],source:step===1?'extend':step===4?'rows':'write',why:`page_size=4。新增页数 = ceil(${d.target}/4) − ceil(6/4) = ${d.newPages}。分配与写值分开；图按页展示写入是教学顺序，不代表 GPU kernel 被拆成两次。本例是同一请求尾页续写，6 不是新请求的 Radix 命中长度。`};}
function drawPrefix(){const d=M.prefix(Number($('#prefix-common').value),$('#prefix-namespace').value==='same',step);
 function row(tokens,name,request){return `<div class="memory-prefix-row"><small>${name}</small><div class="memory-token-groups">`+[0,4].map(start=>`<div class="memory-token-group ${step>=2&&start<d.hit?'reused':''}">`+tokens.slice(start,start+4).map((t,j)=>{const i=start+j;return `<span class="memory-cell ${step===1&&i<d.common?'same':step>=2&&i<d.hit?'hit':step>=2&&request&&i<d.common?'same':''}">${t}</span>`;}).join('')+'</div>').join('')+`<span class="memory-extra">${request?'Z':''}</span></div></div>`;}
 $('#memory-scene').innerHTML=`<h3>${labels.prefix[step]}</h3>`+row(d.cached,'已有缓存 · 每组 4 个 token',false)+row(d.request,`新请求 · ${d.sameNamespace?'相同':'不同'} cache_salt`,true)+(step>=3&&d.hit?`<div class="memory-reuse">${[2,5].slice(0,d.hit/4).map(id=>`<span>请求 → 已有页 ${id}</span>`).join('')}</div>`:`<p class="memory-note">${step===1?`字面连续相同 ${d.common} 个`:'token 标签示意，不代表字符切词'}</p>`)+`<p class="memory-count">${step>=2?`复用 ${d.hit} 个 · 还需计算 ${d.recompute} 个`:'先看相同部分落在哪一页'}</p>`;
 const captions=['缓存已持有 A 到 H 的 KV；新请求还带着尾部 Z，需要继续计算。',`前 ${d.common} 个 token 相同。字面相同长度还不是最终可复用长度。`,!d.sameNamespace?'cache_salt 不同，属于不同缓存身份；即使字面相同，本例也不复用。':`本例按 4 个位置一页，保留完整匹配页：${d.common} → ${d.hit}。不足一页的相同尾部仍要计算。`,d.hit?'请求映射指向缓存原有地址；复用不等于把 K/V 再复制一份。':'没有可复用页，9 个位置都需要计算并获得写地址。'];
 return {caption:captions[step],source:!d.sameNamespace?'salt':step===2?'keyMatch':'match',why:'普通 RadixCache、page_size=4，排除 bigram、特殊模型和分层回载。图比较 9-token 输入与已缓存 8-token 前缀；最终 Z 保留为未缓存输入。匹配还依赖 extra_key 等身份；这里只改变 cache_salt。树节点拆分复制的是索引切片，不是物理 K/V。'};}
function drawSharing(){const d=M.sharing(step),privatePage=(id,active,letters)=>`<div class="memory-page ${active?'':'free'}"><small><span>尾页 ${id}</span><span>${active?'私有':'空闲'}</span></small>${cells(Array.from({length:4},(_,i)=>({label:active&&i<2?letters[i]:'·',state:active&&i<2?'written':''})))}</div>`;
 $('#memory-scene').innerHTML=`<h3>${labels.sharing[step]}</h3><div class="memory-users">${[1,2].map(r=>{const active=d['r'+r],finished=r===1?step>=3:step>=5;return `<div class="memory-user ${active?'active':''}" data-request="R${r}"><strong>R${r}</strong><small>${active?'请求行持有':finished?'请求行已释放':'尚未进入'}</small>${privatePage(r+2,active,r===1?'EF':'XY')}</div>`;}).join('')}</div><svg class="memory-wire" viewBox="0 0 300 48" aria-hidden="true" preserveAspectRatio="none"><path class="${d.r1?'active':''}" d="M75 0 V18 L150 42"/><path class="${d.r2?'active':''}" d="M225 0 V18 L150 42"/></svg><div class="memory-shared ${d.locks?'protected':''}" data-cache-state="${d.pages[0].state}"><div><strong>${d.cached?'同一份共享前缀':'页 2 已归还池内'}</strong><span class="memory-lock">锁 ${d.locks}</span></div><div class="memory-page ${d.cached?'':'free'}"><small><span>物理页 2</span><span>${!d.cached?'可重用':d.evictable?'可驱逐':'受保护'}</span></small>${cells('ABCD'.split('').map(t=>({label:d.cached?t:'·',state:d.cached?'written':''})))}</div></div><div class="memory-pool">图中 3 页容量仍在 KV 池中 · 空闲 ${d.freePages} 页</div>`;
 const captions=['之前计算过的整页前缀仍在缓存；没有请求持有它，可以被驱逐。','R1 复用页 2，并持有自己的尾页 3。缓存节点的锁从 0 变成 1。','R2 指向同一页 2，再领自己的尾页 4。共享页只占一份容量，锁变成 2。','R1 的未满尾页 3 归还池内，请求行也释放。R2 仍在使用页 2，锁只降到 1。','驱逐不能选中受保护的页 2。只有释放 R2 的持有，才可能让它重新成为候选。','R2 的尾页与请求行释放，锁降为 0。页 2 继续留在缓存，直到以后被驱逐。','缓存移除页 2 的索引并归还页号。静态 KV buffer 仍在设备上，之后可以重用这些位置。'];
 return {caption:captions[step],source:step===4?'eligible':step===6?'evict':step===3||step===5?'release':'lock',why:'本图只画一个缓存叶节点和两条请求，各请求已计算 6 个 KV 位置：4 个共享 + 2 个私有。锁是 Radix 节点的 lock_ref，不是分配器的通用引用计数。请求结束时整页前缀留给缓存，不足整页的私有尾部归还；最后生成但未前向的 token 不计作已提交 KV。归还页号不要求把旧字节清零，也不调用系统显存释放。'};}
function render(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));document.querySelectorAll('[data-settings]').forEach(e=>e.hidden=e.dataset.settings!==mode);$('#memory-scene').dataset.step=step;$('#memory-scene').dataset.mode=mode;const d=mode==='extend'?drawExtend():mode==='prefix'?drawPrefix():drawSharing();$('#memory-caption').textContent=d.caption;$('#memory-why').textContent=d.why;const [file,line]=M.sources[d.source];$('#memory-source').href=`https://github.com/sgl-project/sglang/blob/${M.revision}/${file}#L${line}`;$('#memory-status').textContent=`${step+1} / ${last[mode]+1}`;$('#memory-previous').disabled=step===0;$('#memory-next').disabled=step===last[mode];}
function stop(){clearInterval(timer);timer=null;$('#memory-play').textContent='播放';$('#memory-play').setAttribute('aria-pressed','false');}
function reset(){stop();step=0;render();}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;reset();}));document.querySelectorAll('.memory-lab select').forEach(e=>e.addEventListener('change',reset));$('#memory-next').onclick=()=>{stop();step=Math.min(last[mode],step+1);render();};$('#memory-previous').onclick=()=>{stop();step=Math.max(0,step-1);render();};$('#memory-reset').onclick=reset;$('#memory-play').onclick=()=>{if(timer){stop();return;}if(step===last[mode])step=0;$('#memory-play').textContent='暂停';$('#memory-play').setAttribute('aria-pressed','true');render();timer=setInterval(()=>{step++;render();if(step===last[mode])stop();},2600);};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});render();
})();
