#!/usr/bin/env python3
"""Build matching detailed/quick datasets for fixed-admission timing experiments."""
import hashlib
import json
from pathlib import Path
from pp_timing_model import build_model
from build_pp_quick_data import EmbeddedModel, PAGE, derive_quick

SCENARIOS = [
    dict(id='baseline', name='原示例 · 耗时不均', config={}, change='保留原图的全部耗时。不同 PP 级、不同 batch 的前向和 L2 回载时间均不相同。', observe='先看 PP0 L6：提交 M3，同时等待并处理旧 M1 的结果。'),
    dict(id='balanced', name='GPU 计算均衡', config={'gpu_value':5}, change='15 段 GPU 前向都设为 5 u；CPU、L2、通信和 KV 时长保持原值。', observe='计算均衡仍可能有空档。对照 L2 回载、旧结果等待和后续 loop 准备。'),
    dict(id='slow-stage', name='PP1 计算偏慢', config={'stage_scale':[1,2.5,1]}, change='只把 PP1 的五段 GPU 前向时间乘 2.5；其他原始操作时长不变。', observe='跟踪 M3 从 PP0 到 PP2 的输入等待，以及旧 output 回流对其他 loop 的影响。'),
    dict(id='long-batch', name='M3 计算偏长', config={'batch_scale':[1,1,2.5,1,1]}, change='只把 M3 在三个 PP 级的 GPU 时间乘 2.5；不改变请求到达或选批顺序。', observe='高亮 M3 看它的一生，再对照 M4：一份长 batch 如何影响后续提交与等待。'),
    dict(id='short-gpu', name='整体计算较短', config={'gpu_scale':0.4}, change='全部 GPU 前向时间乘 0.4；CPU、L2、通信和 KV 原始操作时长不变。', observe='计算缩短后，准备、通信和旧结果等待占的相对比例可能上升，不能按计算缩短比例推算端到端收益。'),
    dict(id='long-gpu', name='整体计算较长', config={'gpu_scale':2.5}, change='全部 GPU 前向时间乘 2.5；其余原始操作时长不变。', observe='看同一 GPU 前向跨过哪些 CPU loop，以及结果回流与后续前向怎样交错。'),
    dict(id='slow-l2', name='L2 回载偏慢', config={'h2d_scale':3}, change='M2、M4 在各级的 H2D 回载时间乘 3；重新推导 ACK 发布轮次和本地 event 等待。', observe='重点跟踪 M2、M4 的准备到 GPU 开始区间，再到依赖图查看 H2D / layer event 和 ACK。'),
    dict(id='slow-link', name='激活 / output 传输偏慢', config={'link_scale':8}, change='激活与 output 消息的在途时间乘 8；PD KV 传输和控制操作原始耗时不变。', observe='区分“等上级激活”和“等旧 output”两条路径，观察跨 PP 依赖何时成为前置门槛。'),
    dict(id='slow-kv', name='PD KV 传输偏慢', config={'kv_scale':4,'horizon':64}, change='本级 KV 在途时间乘 4；重算 transfer 终态集合、release 名单和清理轮次。', observe='看 GPU 已结束之后的长尾。KV 在途结束之后，还要等轮询和共识推进才能清理。'),
    dict(id='slow-cpu', name='CPU 调度偏慢', config={'cpu_scale':2.5}, change='所有 CPU 操作的服务时间乘 2.5；依赖等待由模型重算，不直接乘倍数。', observe='看前向之间的准备空档，以及调度与共识推进变慢如何影响同一批的结果和释放。'),
]


def encode(value):
    return json.dumps(value, ensure_ascii=False, separators=(',', ':'))


def build():
    outer=EmbeddedModel();outer.feed((PAGE/'index.html').read_text())
    inner=EmbeddedModel();inner.feed(outer.srcdoc)
    original=json.loads(''.join(inner.chunks))
    directory=PAGE/'scenarios';directory.mkdir(exist_ok=True)
    generated=set();catalog=[]
    for scene in SCENARIOS:
        model=build_model(scene['config'])
        if scene['id']=='baseline':
            assert model==original, 'Default scene must reproduce the published model exactly'
        source=encode(model)
        quick=derive_quick(model,source)
        gpu=[[next(e['end']-e['start'] for e in model['events'] if e['kind']=='gpu' and e['r']==r and e['owner']==f'M{m}') for m in range(1,6)] for r in range(3)]
        summary=dict(end=round(model['end'],3),gpu=[[round(t,3) for t in row] for row in gpu],gpuEnd=round(max(e['end'] for e in model['events'] if e['kind']=='gpu'),3),releaseEnd=round(max(model['graph'][f"{x['r']}:{x['n']}:release"]['end'] for x in model['releases']),3),loops=len(model['loops'])//3)
        payload=encode(dict(model=model,quick=quick))
        digest=hashlib.sha256(payload.encode()).hexdigest()[:16]
        filename=f"{scene['id']}.{digest}.json";generated.add(filename)
        (directory/filename).write_text(payload)
        catalog.append({k:v for k,v in scene.items() if k!='config'}|dict(file='scenarios/'+filename,summary=summary))
        print(scene['id'],summary['loops'],'loops/stage, GPU ends',summary['gpuEnd'],'release ends',summary['releaseEnd'])
    for p in directory.glob('*.json'):
        if p.name not in generated:p.unlink()
    (PAGE/'scenario-catalog.js').write_text('// Generated by scripts/build_pp_scenarios.py.\nwindow.PP_SCENARIOS = '+encode(catalog)+';\n')


if __name__=='__main__':build()
