const assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),M=require('../pages/sglang/performance-engineering/model.js');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.OVERVIEW_TEST_URL||'http://127.0.0.1:8765/';await page.goto(base+'sglang/performance-engineering/');await page.waitForLoadState('load');
 const choose=async m=>page.locator(`button[data-mode=${m}]`).click(),next=async()=>page.locator('#perf-next').click(),end=async()=>{while(!await page.locator('#perf-next').isDisabled())await next();};
 const overflow=async label=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label);
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const mode of ['clock','packet','experiment','sample']){await choose(mode);do{assert.equal(await page.locator('[data-settings]:visible').count(),1);assert.equal(await page.locator('.parallel-details').evaluate(e=>e.open),false);await overflow(`${width}/${theme}/${mode}`);assert.match(await page.locator('#perf-source').getAttribute('href'),new RegExp(M.revision));if(await page.locator('#perf-next').isDisabled())break;await next();}while(true);}}}
 await choose('clock');for(const kind of ['base','client','queue','compute']){await page.selectOption('#clock-kind',kind);await end();const d=M.timeline(kind);assert.deepEqual(await page.locator('.perf-stat strong').allTextContents(),[d.ttft,d.e2e,d.total].map(n=>n+' ms'));const heights=await page.locator('.perf-stage').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height));assert.deepEqual(heights,d.segments.map(s=>s.duration));await overflow(kind);}
 await choose('packet');for(const kind of ['token','bundle','single']){await page.selectOption('#packet-kind',kind);await end();const d=M.packets(kind);assert.equal(await page.locator('.perf-token').count(),d.n);assert.equal(await page.locator('.perf-packet').count(),d.chunks.length);assert.match(await page.locator('.perf-stats').innerText(),kind==='single'?/无样本/:/46.7 ms/);await overflow(kind);}
 await choose('experiment');for(const kind of ['concurrency','prefill']){await page.selectOption('#experiment-kind',kind);await end();const {a,b}=M.experiment(kind);assert.equal(await page.locator('.perf-batch').count(),a.groups.length+b.groups.length);const aWidth=await page.locator('.perf-run').first().locator('.perf-batch').evaluateAll(es=>es.reduce((s,e)=>s+e.getBoundingClientRect().width,0)),bWidth=await page.locator('.perf-run').nth(1).locator('.perf-batch').evaluateAll(es=>es.reduce((s,e)=>s+e.getBoundingClientRect().width,0));assert.ok(Math.abs(aWidth/bWidth-a.wall/b.wall)<.01);await overflow(kind);}
 await choose('sample');await page.selectOption('#sample-kind','failure');await end();assert.equal(await page.locator('.perf-request.failed').count(),1);assert.match(await page.locator('.perf-stats').innerText(),/80 ms/);assert.match(await page.locator('.perf-hint').innerText(),/12 token/);
 await choose('clock');await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.perf-stage').first().evaluate(e=>getComputedStyle(e).transitionDuration),'0s');await page.clock.install();await page.locator('#perf-play').click();await page.clock.runFor(2500);assert.equal(await page.locator('#perf-scene').getAttribute('data-step'),'1');await page.locator('#perf-play').click();await page.clock.runFor(5000);assert.equal(await page.locator('#perf-scene').getAttribute('data-step'),'1');await page.locator('#perf-next').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#perf-scene').getAttribute('data-step'),'2');await page.locator('#perf-reset').click();assert.equal(await page.locator('#perf-previous').isDisabled(),true);await page.locator('#perf-play').click();await page.clock.runFor(20000);assert.equal(await page.locator('#perf-play').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('#perf-next').isDisabled(),true);
 const plain=await browser.newPage({javaScriptEnabled:false});await plain.goto(base+'sglang/performance-engineering/');assert.equal(await plain.locator('[data-performance-lab]').isVisible(),false);await plain.locator('.topology-detail summary').first().click();assert.equal(await plain.locator('.perf-flow').first().isVisible(),true);await plain.close();assert.deepEqual(errors,[]);console.log('PASS: four mechanisms, timer and packet branches, exact time proportions, sample bias, playback/keyboard, reduced motion, four widths × two themes, no-JS.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
