const assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),M=require('../pages/sglang/system-overview/model.js');
for(const mode of ['service','inside'])for(let i=0;i<6;i++){const d=M.frame(mode,i);assert.ok(d.visible<=d.sampled);assert.ok(d.sampled===0||d.kv===2);assert.equal(d.step,i);assert.ok(M.sources[d.source]);assert.ok(d.links.every(k=>M.modules[k]));}
assert.deepEqual(M.service.map(d=>[d.from,d.to]),[['client','front'],['front','scheduler'],['scheduler','scheduler'],['scheduler','detokenizer'],['detokenizer','front'],['front','client']]);
assert.deepEqual(M.inside.map(d=>[d.from,d.to]),[['scheduler','cache'],['cache','scheduler'],['scheduler','runner'],['runner','gpu'],['gpu','runner'],['runner','scheduler']]);
assert.equal(M.frame('inside',2).kv,0);assert.equal(M.frame('inside',3).kv,2);assert.equal(M.frame('inside',4).sampled,0);assert.equal(M.frame('inside',5).sampled,1);assert.equal(M.frame('service',4).visible,0);assert.equal(M.frame('service',5).visible,1);
assert.equal(M.topology('tp').replicas,1);assert.deepEqual(M.topology('tp').fractions,[.5,.5]);assert.deepEqual(M.topology('tp').assignments,[['R1'],['R1']]);assert.equal(M.topology('dp').replicas,2);assert.deepEqual(M.topology('dp').assignments,[['R1'],['R2']]);assert.deepEqual(M.topology('pd').fractions,[1,1]);assert.deepEqual(M.topology('pd').assignments,[['R1 · P'],['R1 · D']]);
assert.equal(Object.keys(M.modules).length,11);assert.equal(new Set(Object.values(M.modules).map(x=>x[1])).size,11);for(const bad of [-1,6,.5])assert.throws(()=>M.frame('service',bad));assert.throws(()=>M.frame('bad'));assert.throws(()=>M.topology('bad'));
if(process.env.SGLANG_SOURCE_DIR)for(const [key,[file,line,symbol]] of Object.entries(M.sources)){const code=execFileSync('git',['-C',process.env.SGLANG_SOURCE_DIR,'show',`${M.revision}:${file}`],{encoding:'utf8'});assert.ok(code.split('\n')[line-1].includes(symbol),`${key}: line ${line}: ${code.split('\n')[line-1]}`);}
console.log(`PASS: process versus responsibility boundaries, KV/output visibility order, replica/rank distinctions, module coverage; ${process.env.SGLANG_SOURCE_DIR?Object.keys(M.sources).length:0} source anchors.`);
