const assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),M=require('../pages/sglang/scheduling/model.js');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.OVERVIEW_TEST_URL||'http://127.0.0.1:8765/';await page.goto(base+'sglang/scheduling/');await page.waitForLoadState('load');
 const choose=async m=>page.locator(`button[data-mode=${m}]`).click(),next=async()=>page.locator('#schedule-next').click(),end=async()=>{while(!await page.locator('#schedule-next').isDisabled())await next();};
 const geometry=async label=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label);assert.deepEqual(await page.locator('.schedule-token').evaluateAll(es=>es.filter(e=>e.scrollWidth>e.clientWidth+1).map(e=>e.textContent)),[],label);};
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const mode of ['admission','chunk','retract']){await choose(mode);do{assert.equal(await page.locator('[data-settings]:visible').count(),1);assert.equal(await page.locator('.parallel-details').evaluate(e=>e.open),false);await geometry(`${width}/${theme}/${mode}`);assert.match(await page.locator('#schedule-source').getAttribute('href'),new RegExp(M.revision));if(await page.locator('#schedule-next').isDisabled())break;await next();}while(true);}}}
 await choose('admission');for(const policy of ['fcfs','lpm'])for(const scenario of Object.keys(M.cases)){await page.selectOption('#schedule-policy',policy);await page.selectOption('#admission-case',scenario);const events=M.admission(policy,scenario);for(let i=0;i<events.length;i++){const d=events[i];assert.deepEqual(await page.locator('.schedule-queue .schedule-request').evaluateAll(es=>es.map(e=>e.dataset.request)),d.waiting);assert.deepEqual(await page.locator('.schedule-batch .schedule-chip').allTextContents(),d.admitted);if(scenario==='first'&&policy==='fcfs'&&d.kind==='commit')assert.equal(await page.locator('.schedule-bar b').count(),1);await geometry(`${policy}/${scenario}/${i}`);if(i<events.length-1)await next();}}
 await choose('chunk');for(const cap of [4,6,8]){await page.selectOption('#chunk-cap',String(cap));await end();const d=M.chunks(cap).at(-1);assert.equal(await page.locator('.schedule-round').count(),d.history.length);assert.equal(await page.locator('.schedule-token').filter({hasText:/^L$/}).count(),10);assert.equal(await page.locator('.schedule-token').filter({hasText:/^S$/}).count(),2);await geometry(`chunk${cap}`);}
 await choose('retract');for(const scenario of ['resume','full','cache']){await page.selectOption('#retract-case',scenario);const last=M.retraction(scenario).last;for(let i=0;i<=last;i++){const d=M.retraction(scenario,i);for(const [id,n]of [['R1',d.r1],['R2',d.r2],['cache',d.cache],['empty',d.free]])assert.equal(await page.locator(`[data-owner=${id}]`).count(),n);assert.deepEqual(await page.locator('.schedule-output span').allTextContents(),d.output);if(scenario==='full'&&i>=3)assert.match(await page.locator('.schedule-zone.abort').innerText(),/已终止/);await geometry(`${scenario}/${i}`);if(i<last)await next();}}
 await choose('chunk');await page.emulateMedia({reducedMotion:'reduce'});await page.clock.install();await page.locator('#schedule-play').click();await page.clock.runFor(2900);assert.equal(await page.locator('#schedule-scene').getAttribute('data-step'),'1');await page.locator('#schedule-play').click();await page.clock.runFor(6000);assert.equal(await page.locator('#schedule-scene').getAttribute('data-step'),'1');await page.locator('#schedule-next').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#schedule-scene').getAttribute('data-step'),'2');await page.locator('#schedule-reset').click();assert.equal(await page.locator('#schedule-previous').isDisabled(),true);await page.locator('#schedule-play').click();await page.clock.runFor(22000);assert.equal(await page.locator('#schedule-play').getAttribute('aria-pressed'),'false');
 const plain=await browser.newPage({javaScriptEnabled:false});await plain.goto(base+'sglang/scheduling/');assert.equal(await plain.locator('[data-schedule-lab]').isVisible(),false);await plain.locator('.topology-detail summary').first().click();assert.equal(await plain.locator('.schedule-static').first().isVisible(),true);await plain.close();assert.deepEqual(errors,[]);console.log('PASS: queue-to-batch flow, all budget branches, chunk allocations, KV recovery and abort, four widths × two themes, playback/keyboard, reduced motion, no-JS.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
