const assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),M=require('../pages/sglang/model-execution/model.js');
for(const n of [1,3,4,5])for(const condition of ['ready','off','override'])for(let step=0;step<=4;step++){
 const d=M.graph(n,condition,step);assert.equal(d.real.length,n);assert.equal(d.eligible,condition==='ready'&&n<=4);assert.deepEqual(d.slots.filter(x=>x!==null),d.real);assert.equal(d.slots.length,step>=2&&d.eligible?d.bucket:n);assert.deepEqual(d.outputs,step>=4?d.real:[]);assert.ok(d.outputs.every(x=>x!==null));
}assert.deepEqual(M.graph(3,'ready',2).slots,['R1','R2','R3',null]);assert.equal(M.graph(5).path,'eager');assert.throws(()=>M.graph(0));
for(const m of [1,16,256]){
 const d=M.matrix(m),math=M.matrix(m,'compute'),memory=M.matrix(m,'memory');assert.equal(d.flops,2*m*4096*4096);assert.equal(d.bytes,2*(2*m*4096+4096*4096));assert.equal(math.memoryMs,d.memoryMs);assert.equal(memory.mathMs,d.mathMs);assert.equal(math.mathMs,d.mathMs/2);assert.equal(memory.memoryMs,d.memoryMs/2);assert.equal(d.weightBytes,M.matrix(1).weightBytes);assert.ok(d.lowerMs>=d.mathMs&&d.lowerMs>=d.memoryMs);
}assert.equal(M.matrix(1).limit,'memory');assert.equal(M.matrix(256).limit,'math');assert.equal(M.matrix(1,'compute').lowerMs,M.matrix(1).lowerMs);assert.equal(M.matrix(256,'memory').lowerMs,M.matrix(256).lowerMs);assert.throws(()=>M.matrix(0));assert.equal(M.trace.at(-1).to,'Scheduler');assert.equal(M.trace[5].data,'kernel');assert.equal(M.trace[6].data,'logits');
if(process.env.SGLANG_SOURCE_DIR)for(const [key,[file,line,symbol]] of Object.entries(M.sources)){const code=execFileSync('git',['-C',process.env.SGLANG_SOURCE_DIR,'show',`${M.revision}:${file}`],{encoding:'utf8'});assert.ok(code.split('\n')[line-1].includes(symbol),`${key}: line ${line}: ${code.split('\n')[line-1]}`);}
console.log(`PASS: graph eligibility, real-request conservation, padding isolation, matrix arithmetic and single-resource limits; ${process.env.SGLANG_SOURCE_DIR?Object.keys(M.sources).length:0} source anchors.`);
