const assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),M=require('../pages/sglang/serving-operations/model.js');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.OVERVIEW_TEST_URL||'http://127.0.0.1:8765/';await page.goto(base+'sglang/serving-operations/');await page.waitForLoadState('load');
 const choose=async m=>page.locator(`button[data-mode=${m}]`).click(),next=async()=>page.locator('#ops-next').click(),end=async()=>{while(!await page.locator('#ops-next').isDisabled())await next();};
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const mode of ['health','admission','cancel','drain']){await choose(mode);do{assert.equal(await page.locator('[data-settings]:visible').count(),1);assert.equal(await page.locator('.parallel-details').evaluate(e=>e.open),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width}/${theme}/${mode}`);assert.match(await page.locator('#ops-source').getAttribute('href'),new RegExp(M.revision));if(await page.locator('#ops-next').isDisabled())break;await next();}while(true);}}}
 await choose('health');for(const kind of ['startup','activity','stall','light']){await page.selectOption('#health-kind',kind);await end();assert.match(await page.locator('.ops-badge').innerText(),new RegExp(kind==='stall'?'503':'200'));if(kind==='activity')assert.match(await page.locator('.ops-pair').innerText(),/R1[\s\S]*排队/);}
 await choose('admission');for(const kind of ['both','b-down','circuit','none']){await page.selectOption('#worker-kind',kind);await end();if(kind==='none')assert.equal(await page.locator('.ops-node.selected').count(),0);else{const lists=await page.locator('.ops-pair .ops-chips').allTextContents();assert.deepEqual(lists,M.route(kind,3).assigned.map(xs=>xs.join('')||'空'));}}
 await page.selectOption('#admission-kind','queue');for(const cap of [1,2]){await page.selectOption('#queue-capacity',String(cap));await next();await next();await next();assert.equal(await page.locator('.ops-rejected .reject').count(),3-cap);await next();assert.match(await page.locator('.ops-node').nth(1).innerText(),/R1/);await next();assert.match(await page.locator('.ops-node').first().innerText(),/R4/);}
 await choose('cancel');for(const kind of ['disconnect','waiting']){await page.selectOption('#cancel-kind',kind);await next();assert.equal(await page.locator('.ops-node .ops-chip:not(.empty)').count(),2);await next();if(kind==='waiting')assert.equal(await page.locator('animateMotion').count(),0,'scheduler-generated abort is not a TM-to-scheduler message');await next();assert.equal(await page.locator('.ops-node .ops-chip:not(.empty)').count(),1);const positions=await page.locator('.ops-wire').evaluate(svg=>{svg.pauseAnimations();const c=svg.querySelector('circle');return [.1,.8].map(t=>{svg.setCurrentTime(t);return c.getCTM().f;});});assert.ok(positions[1]<positions[0],'abort echo moves up to frontend');await end();assert.equal(await page.locator('.ops-node .ops-chip:not(.empty)').count(),0);}
 await choose('drain');for(const kind of ['normal','arrivals','stuck']){await page.selectOption('#drain-kind',kind);await end();const text=await page.locator('#ops-scene').innerText();if(kind==='normal')assert.match(text,/已观察到退出/);if(kind==='arrivals'){assert.match(text,/R3/);assert.doesNotMatch(text,/ShutdownReq →/);}if(kind==='stuck'){assert.match(text,/强制终止路径/);assert.doesNotMatch(text,/已观察到退出/);}}
 await choose('cancel');await page.selectOption('#cancel-kind','disconnect');await next();await next();await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelectorAll('animateMotion').length===0);await page.emulateMedia({reducedMotion:'no-preference'});
 await choose('health');await page.clock.install();await page.locator('#ops-play').click();await page.clock.runFor(2500);assert.equal(await page.locator('#ops-scene').getAttribute('data-step'),'1');await page.locator('#ops-play').click();await page.clock.runFor(5000);assert.equal(await page.locator('#ops-scene').getAttribute('data-step'),'1');await page.locator('#ops-next').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#ops-scene').getAttribute('data-step'),'2');await page.locator('#ops-reset').click();assert.equal(await page.locator('#ops-previous').isDisabled(),true);
 const plain=await browser.newPage({javaScriptEnabled:false});await plain.goto(base+'sglang/serving-operations/');assert.equal(await plain.locator('[data-serving-lab]').isVisible(),false);await plain.locator('.topology-detail summary').first().click();assert.equal(await plain.locator('.ops-static').first().isVisible(),true);await plain.close();assert.deepEqual(errors,[]);console.log('PASS: startup/probes, eligible routing, queue capacity, cancel/echo direction, drain branches, reduced motion, playback/keyboard, four widths × two themes, no-JS.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
