const assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),M=require('../pages/sglang/scheduling/model.js');
for(const policy of ['fcfs','lpm'])for(const scenario of Object.keys(M.cases)){
 const events=M.admission(policy,scenario),final=events.at(-1),first=policy==='fcfs'?'R1':'R2',expected=scenario==='room'?(policy==='fcfs'?['R1','R2','R3']:['R2','R1','R3']):scenario==='exact'?[]:[first];assert.deepEqual(final.admitted,expected,`${policy}/${scenario}`);
 for(const d of events){assert.equal(d.admitted.length+d.waiting.length,3);assert.equal(new Set([...d.admitted,...d.waiting]).size,3);assert.ok(d.admitted.length<=d.config.rows);assert.equal(d.available+d.offset+d.protectedTokens+d.trial,d.config.kv);if(d.kind==='commit')assert.ok(d.available>0);}
 const blocked=events.findIndex(d=>d.kind==='blocked');if(blocked>=0)assert.ok(events.slice(blocked+1).every(d=>d.kind==='ready'));assert.equal(final.trial,0);
}
const fcfs=M.admission('fcfs','first');assert.equal(fcfs.find(d=>d.kind==='commit').usedInput,6);assert.ok(fcfs.find(d=>d.kind==='stop').admitted.includes('R1'));assert.equal(M.admission('lpm','compute').find(d=>d.kind==='blocked').current,'R1');
const memory=M.admission('fcfs','memory'),pin=memory.find(d=>d.kind==='check'&&d.current==='R2'),reject=memory.find(d=>d.kind==='blocked');assert.equal(pin.available,-1);assert.equal(reject.available,3);assert.equal(reject.protectedTokens,0);assert.equal(reject.offset,9);for(const policy of ['fcfs','lpm'])assert.equal(M.admission(policy,'exact').find(d=>d.kind==='blocked').reason,'kv');
for(const cap of [4,6,8]){const events=M.chunks(cap);for(const d of events){assert.equal(d.left+d.history.reduce((n,p)=>n+p.l,0),10);assert.equal(d.shortLeft+d.history.reduce((n,p)=>n+p.s,0),2);for(const p of d.history)assert.ok(p.l+p.s<=cap);if(d.kind==='plan'&&d.plan.s)assert.equal(d.plan.l,d.left,'short work only fits after active continuation');}assert.equal(events.at(-1).left,0);assert.equal(events.at(-1).shortLeft,0);assert.deepEqual(events.at(-1).history.map(p=>[p.l,p.s]),cap===4?[[4,0],[4,0],[2,2]]:cap===6?[[6,0],[4,2]]:[[8,0],[2,2]]);}
for(const scenario of ['resume','full','cache']){const last=M.retraction(scenario).last;for(let i=0;i<=last;i++){const d=M.retraction(scenario,i);assert.equal(d.r1+d.r2+d.cache+d.free,d.capacity);assert.ok(d.free>=0);assert.equal(d.output[0],'a');if(scenario!=='cache'&&i>=2&&i<6){assert.equal(d.r2,0);assert.equal(d.row,false);assert.deepEqual(d.output,['a']);}}}
assert.equal(M.retraction('resume',2).free,4);assert.equal(M.retraction('resume',3).location,'waiting');assert.equal(M.retraction('full',3).location,'aborted');assert.equal(M.retraction('resume',5).cache,9);assert.equal(M.retraction('resume',6).recompute,5);assert.deepEqual(M.retraction('resume',6).output,['a']);assert.deepEqual(M.retraction('resume',7).output,['a','b']);assert.equal(M.retraction('cache',1).free,2);assert.equal(M.retraction('cache',2).location,'running');
if(process.env.SGLANG_SOURCE_DIR)for(const [key,[file,line,symbol]] of Object.entries(M.sources)){const code=execFileSync('git',['-C',process.env.SGLANG_SOURCE_DIR,'show',`${M.revision}:${file}`],{encoding:'utf8'});assert.ok(code.split('\n')[line-1].includes(symbol),`${key}: line ${line}: ${code.split('\n')[line-1]}`);}
console.log(`PASS: order/admission separation, first-input exception, strict KV boundary, temporary pin rollback, stop-after-commit, chunk work conservation, recovery and queue rejection; ${process.env.SGLANG_SOURCE_DIR?Object.keys(M.sources).length:0} source anchors.`);
