const assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),M=require('../pages/sglang/kv-memory/model.js');
for(const target of [8,9,11])for(let step=0;step<=4;step++){
 const d=M.extend(target,step);assert.equal(d.newPages,target===8?0:1);assert.equal(new Set(d.mapping).size,d.mapping.length);assert.deepEqual(d.mapping.slice(0,6),[4,5,6,7,28,29]);assert.equal(d.mapping.length,step?target:6);assert.equal(d.written,step>=3?target:step>=2?8:6);assert.equal(d.ownedPages,2+Number(step>0&&target>8));assert.equal(d.pages.filter(p=>!p.free).length,d.ownedPages);assert.equal(d.pages.flatMap(p=>p.cells).filter(c=>c.state==='written').length,d.written);assert.equal(d.pages.flatMap(p=>p.cells).filter(c=>c.state==='reserved').length,d.mapping.length-d.written);assert.ok(d.mapping.every(s=>Math.floor(s/4)>0));
}assert.deepEqual(M.extend(11,1).added,[30,31,12,13,14]);assert.equal(M.extend(9,4).mapping[8],12);assert.equal(M.extend(8,4).pages[2].free,true);assert.throws(()=>M.extend(7));
for(const common of [3,6,8])for(const ns of [true,false])for(let step=0;step<4;step++){
 const d=M.prefix(common,ns,step);assert.equal(d.request.length,9);assert.equal(d.request.at(-1),'Z');assert.equal(d.hit,ns?({3:0,6:4,8:8})[common]:0);assert.equal(d.hit%4,0);assert.equal(d.recompute+d.hit,9);assert.equal(d.reused.length,step===3?d.hit:0);assert.equal(d.newCopies,0);assert.ok(d.reused.every(s=>[8,9,10,11,20,21,22,23].includes(s)));
}assert.deepEqual(M.prefix(6,true,3).reused,[8,9,10,11]);assert.deepEqual(M.prefix(8,false,3).reused,[]);
for(let step=0;step<=6;step++){const d=M.sharing(step);assert.equal(d.locks,Number(d.r1)+Number(d.r2));assert.equal(d.pages.length,3);assert.equal(d.bufferPages,3);assert.equal(d.freePages+d.pages.filter(p=>p.state!=='free').length,3);assert.equal(d.evictable,d.cached&&d.locks===0);assert.equal(d.pages.filter(p=>p.state==='private').length,d.locks);if(d.locks)assert.equal(d.pages[0].state,'protected');}
assert.equal(M.sharing(3).r1,false);assert.equal(M.sharing(3).r2,true);assert.equal(M.sharing(3).locks,1);assert.equal(M.sharing(4).evictAttempt,true);assert.equal(M.sharing(4).freePages,M.sharing(3).freePages);assert.equal(M.sharing(5).cached,true);assert.equal(M.sharing(5).freePages,2);assert.equal(M.sharing(6).freePages,3);
if(process.env.SGLANG_SOURCE_DIR)for(const [key,[file,line,symbol]] of Object.entries(M.sources)){const code=execFileSync('git',['-C',process.env.SGLANG_SOURCE_DIR,'show',`${M.revision}:${file}`],{encoding:'utf8'});assert.ok(code.split('\n')[line-1].includes(symbol),`${key}: line ${line}: ${code.split('\n')[line-1]}`);}
console.log(`PASS: tail-page addresses, allocation/write separation, aligned reuse and namespace, shared ownership, protected eviction and pool conservation; ${process.env.SGLANG_SOURCE_DIR?Object.keys(M.sources).length:0} source anchors.`);
