const assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),M=require('../pages/sglang/kv-memory/model.js');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.OVERVIEW_TEST_URL||'http://127.0.0.1:8765/';await page.goto(base+'sglang/kv-memory/');await page.waitForLoadState('load');
 const choose=async m=>page.locator(`button[data-mode=${m}]`).click(),next=async()=>page.locator('#memory-next').click(),end=async()=>{while(!await page.locator('#memory-next').isDisabled())await next();};
 const geometry=async label=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label);assert.deepEqual(await page.locator('.memory-cell').evaluateAll(es=>es.filter(e=>e.scrollWidth>e.clientWidth+1).map(e=>e.textContent)),[],label);};
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const mode of ['extend','prefix','sharing']){await choose(mode);do{assert.equal(await page.locator('[data-settings]:visible').count(),1);assert.equal(await page.locator('.parallel-details').evaluate(e=>e.open),false);await geometry(`${width}/${theme}/${mode}`);assert.match(await page.locator('#memory-source').getAttribute('href'),new RegExp(M.revision));if(mode==='sharing'){const d=M.sharing(Number(await page.locator('#memory-scene').getAttribute('data-step')));assert.equal(await page.locator('.memory-user.active').count(),d.locks);assert.equal(await page.locator('.memory-wire .active').count(),d.locks);assert.equal(await page.locator('.memory-shared').getAttribute('data-cache-state'),d.pages[0].state);assert.match(await page.locator('.memory-pool').innerText(),new RegExp(`空闲 ${d.freePages} 页`));}if(await page.locator('#memory-next').isDisabled())break;await next();}while(true);}}}
 await choose('extend');for(const target of [8,9,11]){await page.selectOption('#extend-length',String(target));await next();assert.equal(await page.locator('.memory-cell.reserved').count(),target-6);await next();assert.equal(await page.locator('.memory-cell.written').count(),8);assert.match(await page.locator('.memory-focus').innerText(),/原来的尾页已写满/);await end();assert.equal(await page.locator('.memory-cell.written').count(),target);assert.equal(await page.locator('.memory-cell.focus').getAttribute('data-slot'),String(M.extend(target,4).mapping.at(-1)));assert.equal(await page.locator('[data-page-id="3"].free').count(),target===8?1:0);await geometry(`target${target}`);}
 await choose('prefix');for(const common of [3,6,8])for(const ns of ['same','different']){await page.selectOption('#prefix-common',String(common));await page.selectOption('#prefix-namespace',ns);await next();assert.equal(await page.locator('.memory-cell.same').count(),common*2);await next();const d=M.prefix(common,ns==='same',2);assert.equal(await page.locator('.memory-cell.hit').count(),d.hit*2);await end();assert.equal(await page.locator('.memory-reuse span').count(),d.hit/4);assert.match(await page.locator('.memory-count').innerText(),new RegExp(`复用 ${d.hit} 个`));await geometry(`${common}/${ns}`);}
 await choose('sharing');await page.emulateMedia({reducedMotion:'reduce'});await page.clock.install();await page.locator('#memory-play').click();await page.clock.runFor(2700);assert.equal(await page.locator('#memory-scene').getAttribute('data-step'),'1');await page.locator('#memory-play').click();await page.clock.runFor(6000);assert.equal(await page.locator('#memory-scene').getAttribute('data-step'),'1');await page.locator('#memory-next').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#memory-scene').getAttribute('data-step'),'2');await page.locator('#memory-reset').click();assert.equal(await page.locator('#memory-previous').isDisabled(),true);await page.locator('#memory-play').click();await page.clock.runFor(18000);assert.equal(await page.locator('#memory-play').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('#memory-scene').getAttribute('data-step'),'6');
 const plain=await browser.newPage({javaScriptEnabled:false});await plain.goto(base+'sglang/kv-memory/');assert.equal(await plain.locator('[data-memory-lab]').isVisible(),false);await plain.locator('.topology-detail summary').first().click();assert.equal(await plain.locator('.memory-static').first().isVisible(),true);await plain.close();assert.deepEqual(errors,[]);console.log('PASS: mapped slots, partial-page writes, all prefix branches, shared-page protection, four widths × two themes, playback/keyboard, reduced motion, no-JS.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
