const assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),M=require('../pages/sglang/performance-engineering/model.js');
const base=M.timeline(),client=M.timeline('client'),queue=M.timeline('queue');
assert.equal(base.ttft,220);assert.equal(base.e2e,360);assert.equal(base.total,440);assert.equal(client.ttft,base.ttft);assert.equal(client.e2e,base.e2e);assert.equal(client.total,base.total+120);assert.equal(queue.ttft,base.ttft+120);assert.equal(queue.e2e,base.e2e+120);assert.equal(M.timeline('compute').e2e,base.e2e-50);
for(const k of ['base','client','queue','compute']){const d=M.timeline(k);assert.equal(d.segments.reduce((sum,s)=>sum+s.duration,0),d.total);for(let i=1;i<d.segments.length;i++)assert.equal(d.segments[i].start,d.segments[i-1].end);}
assert.deepEqual(M.packets('token').itls,[40,40,40]);assert.deepEqual(M.packets('bundle').itls,[40,40,40]);assert.notEqual(M.packets('bundle').chunks.length,M.packets('token').chunks.length);assert.equal(M.packets().tpot,140/3);assert.equal(M.packets('single').tpot,null);assert.deepEqual(M.packets('single').itls,[]);
const a=M.schedule(1),b=M.schedule(3),fast=M.schedule(3,2);assert.equal(a.wall,720);assert.equal(b.wall,360);assert.ok(b.throughput>a.throughput&&b.e2e>a.e2e);assert.equal(a.readyMean,420);assert.equal(b.readyMean,270);assert.equal(b.wall/fast.wall,4/3);assert.equal(fast.tpot,b.tpot);for(const d of [a,b,fast])assert.deepEqual(d.groups.flatMap(g=>g.ids),[1,2,3,4,5,6]);assert.throws(()=>M.schedule(0));
const all=M.sample(),failed=M.sample('failure');assert.equal(all.mean,185);assert.equal(failed.mean,80);assert.equal(all.throughput,16);assert.equal(failed.throughput,12);assert.equal(failed.failed,1);assert.ok(Math.abs(all.p95-437)<1e-9);assert.equal(M.percentile([],0.95),null);
if(process.env.SGLANG_SOURCE_DIR)for(const [key,[file,line,symbol]] of Object.entries(M.sources)){const code=execFileSync('git',['-C',process.env.SGLANG_SOURCE_DIR,'show',`${M.revision}:${file}`],{encoding:'utf8'});assert.ok(code.split('\n')[line-1].includes(symbol),`${key}: line ${line}: ${code.split('\n')[line-1]}`);}
console.log(`PASS: timer boundaries, packets versus tokens, missing TPOT, conserved requests, throughput/latency tradeoff, partial speedup and success bias; ${process.env.SGLANG_SOURCE_DIR?Object.keys(M.sources).length:0} fixed anchors.`);
