const assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),M=require('../pages/sglang/model-execution/model.js');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.OVERVIEW_TEST_URL||'http://127.0.0.1:8765/';await page.goto(base+'sglang/model-execution/');await page.waitForLoadState('load');
 const choose=async m=>page.locator(`button[data-mode=${m}]`).click(),next=async()=>page.locator('#exec-next').click(),end=async()=>{while(!await page.locator('#exec-next').isDisabled())await next();};
 const overflow=async label=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label);
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const mode of ['chain','graph','hardware']){await choose(mode);do{assert.equal(await page.locator('[data-settings]:visible').count(),1);assert.equal(await page.locator('.parallel-details').evaluate(e=>e.open),false);await overflow(`${width}/${theme}/${mode}`);const step=Number(await page.locator('#exec-scene').getAttribute('data-step'));if(mode==='chain'){assert.equal(await page.locator('.exec-actor').first().innerText(),M.trace[step].from);assert.equal(await page.locator('.exec-actor').last().innerText(),M.trace[step].to);}if(mode!=='hardware')assert.match(await page.locator('#exec-source').getAttribute('href'),new RegExp(M.revision));if(await page.locator('#exec-next').isDisabled())break;await next();}while(true);}}}
 await choose('chain');await next();assert.match(await page.locator('.exec-payload').innerText(),/p3 → 槽 11/);await next();assert.match(await page.locator('.exec-payload').innerText(),/分界 \[0, 4, 7\]/);await next();await next();assert.deepEqual(await page.locator('.exec-chip').allTextContents(),['Q','K','V']);await next();assert.deepEqual(await page.locator('.exec-chip').allTextContents(),['Q','K buffer','V buffer']);await next();assert.equal(await page.locator('.exec-score').count(),3);await end();assert.deepEqual(await page.locator('.exec-chip').allTextContents(),['R1 → b','R2 → a']);
 await choose('graph');for(const n of [1,3,4,5])for(const condition of ['ready','off','override']){await page.selectOption('#graph-count',String(n));await page.selectOption('#graph-condition',condition);await next();await next();const d=M.graph(n,condition,2);assert.equal(await page.locator('.exec-buffer .exec-chip').count(),d.slots.length);assert.equal(await page.locator('.exec-buffer .pad').count(),d.slots.length-n);assert.equal(await page.locator('.exec-branch .chosen').count(),1);assert.match(await page.locator('.exec-branch .chosen').innerText(),d.eligible?/CUDA Graph/:/Eager/);await end();assert.equal(await page.locator('.exec-output .exec-chip').count(),n);assert.equal(await page.locator('.exec-output .pad').count(),0);await overflow(`${n}/${condition}`);}
 await choose('hardware');for(const m of [1,16,256])for(const upgrade of ['base','compute','memory']){await page.selectOption('#matrix-rows',String(m));await page.selectOption('#hardware-upgrade',upgrade);await end();const d=M.matrix(m,upgrade),b=M.matrix(m);assert.match(await page.locator('.exec-equation').innerText(),new RegExp(d.lowerMs.toFixed(3)));const widths=await page.locator('.exec-bar-track i').evaluateAll(es=>es.map(e=>parseFloat(e.style.width)));assert.ok(Math.abs(widths[0]/widths[1]-d.mathMs/d.memoryMs)<1e-5);assert.equal(await page.locator('.weights i').count(),16);await overflow(`${m}/${upgrade}`);}
 await choose('chain');const ys=await page.locator('.exec-wire').evaluate(svg=>{svg.pauseAnimations();return [.1,.9].map(t=>{svg.setCurrentTime(t);return svg.querySelector('circle').getCTM().f;});});assert.ok(ys[1]>ys[0]);await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelectorAll('animateMotion').length===0);await page.clock.install();await page.locator('#exec-play').click();await page.clock.runFor(2500);assert.equal(await page.locator('#exec-scene').getAttribute('data-step'),'1');await page.locator('#exec-play').click();await page.clock.runFor(5000);assert.equal(await page.locator('#exec-scene').getAttribute('data-step'),'1');await page.locator('#exec-next').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#exec-scene').getAttribute('data-step'),'2');await page.locator('#exec-reset').click();assert.equal(await page.locator('#exec-previous').isDisabled(),true);await page.locator('#exec-play').click();await page.clock.runFor(20000);assert.equal(await page.locator('#exec-play').getAttribute('aria-pressed'),'false');
 const plain=await browser.newPage({javaScriptEnabled:false});await plain.goto(base+'sglang/model-execution/');assert.equal(await plain.locator('[data-execution-lab]').isVisible(),false);await plain.locator('.topology-detail summary').first().click();assert.equal(await plain.locator('.exec-flow').first().isVisible(),true);await plain.close();assert.deepEqual(errors,[]);console.log('PASS: execution handoffs, graph branches/padding/trim, hardware cost ratios, motion direction, reduced motion, playback/keyboard, four widths × two themes, no-JS.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
