const assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const M=require('../pages/sglang/advanced-generation/model.js');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.OVERVIEW_TEST_URL||'http://127.0.0.1:8765/';await page.goto(base+'sglang/advanced-generation/');await page.waitForLoadState('load');
 const choose=async m=>page.locator(`button[data-mode=${m}]`).click(),next=async()=>page.locator('#gen-next').click(),end=async()=>{while(!await page.locator('#gen-next').isDisabled())await next();};
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const mode of ['state','speculative','grammar']){
  await choose(mode);do{assert.equal(await page.locator('[data-settings]:visible').count(),1);assert.equal(await page.locator('.parallel-details').evaluate(e=>e.open),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width}/${theme}/${mode}`);assert.match(await page.locator('#gen-source').getAttribute('href'),new RegExp(M.revision));if(await page.locator('#gen-next').isDisabled())break;await next();}while(true);
 }}}
 await choose('state');for(const kind of ['attention','recurrent','hybrid']){await page.selectOption('#state-kind',kind);for(let i=0;i<4;i++)await next();if(kind!=='attention')assert.equal(await page.locator('.state-box strong').innerText(),'5.5');if(kind!=='recurrent')assert.equal(await page.locator('.memory-slot.filled').count(),4);await next();if(kind!=='attention')assert.equal(await page.locator('.state-box strong').innerText(),'4');if(kind!=='recurrent')assert.equal(await page.locator('.memory-slot.filled').count(),2);}
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>getComputedStyle(document.querySelector('.state-arrow'),'::before').animationName==='none');assert.equal(await page.locator('.state-arrow').evaluate(e=>getComputedStyle(e,'::before').animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});
 await choose('speculative');for(const accepted of [0,2,4]){await page.selectOption('#spec-accept',String(accepted));await end();const d=M.speculate(accepted);assert.deepEqual(await page.locator('.output-tokens .gen-token').allTextContents(),d.output);assert.deepEqual(await page.locator('.valid-kv .gen-token.accepted').allTextContents(),d.validKV);assert.equal(await page.locator('.verify-cell.invalid').count(),4-accepted);assert.equal(await page.locator('.valid-kv .pending').innerText(),'z 待计算');}
 await choose('grammar');for(const pref of ['yes','no']){await page.selectOption('#grammar-prefer',pref);await next();assert.equal(await page.locator('.vocab-row.masked').count(),3);assert.equal(await page.locator('[data-token="!"]').getAttribute('class'),'vocab-row masked ');await next();assert.equal(await page.locator('.grammar-path .current').innerText(),pref==='yes'?'y':'no');await end();assert.equal(await page.locator('.grammar-path .current').innerText(),'结束');assert.equal(await page.locator('.vocab-row.selected').getAttribute('data-token'),'EOS');}
 await choose('state');await page.clock.install();await page.locator('#gen-play').click();await page.clock.runFor(2500);assert.equal(await page.locator('#gen-scene').getAttribute('data-step'),'1');await page.locator('#gen-play').click();await page.clock.runFor(4900);assert.equal(await page.locator('#gen-scene').getAttribute('data-step'),'1');await page.locator('#gen-next').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#gen-scene').getAttribute('data-step'),'2');await page.locator('#gen-reset').click();assert.equal(await page.locator('#gen-previous').isDisabled(),true);
 const plain=await browser.newPage({javaScriptEnabled:false});await plain.goto(base+'sglang/advanced-generation/');assert.equal(await plain.locator('[data-generation-lab]').isVisible(),false);await plain.locator('.topology-detail summary').first().click();assert.equal(await plain.locator('.gen-static').first().isVisible(),true);await plain.close();assert.deepEqual(errors,[]);console.log('PASS: state forms/rollback, acceptance branches, output/KV offset, grammar masking/paths, playback/keyboard, reduced motion, four widths × two themes, no-JS.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
