const assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),M=require('../pages/sglang/system-overview/model.js');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.OVERVIEW_TEST_URL||'http://127.0.0.1:8765/';await page.goto(base+'sglang/system-overview/');await page.waitForLoadState('load');
 const choose=async mode=>page.locator(`button[data-mode=${mode}]`).click(),next=async()=>page.locator('#system-next').click();
 const geometry=async label=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label);assert.deepEqual(await page.locator('.system-node,.system-device,.system-payload').evaluateAll(es=>es.filter(e=>e.scrollWidth>e.clientWidth+1).map(e=>e.textContent)),[],label);assert.deepEqual(await page.locator('.system-map').evaluateAll(maps=>maps.flatMap(map=>{const es=[...map.querySelectorAll('.system-node,.system-payload,.system-boundary>small')];return es.flatMap((a,i)=>es.slice(i+1).filter(b=>{const x=a.getBoundingClientRect(),y=b.getBoundingClientRect();return Math.min(x.right,y.right)-Math.max(x.left,y.left)>2&&Math.min(x.bottom,y.bottom)-Math.max(x.top,y.top)>2;}).map(b=>`${a.textContent}/${b.textContent}`));})),[],label+' overlapping labels');};
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const mode of ['service','inside']){await choose(mode);for(let step=0;step<6;step++){const d=M.frame(mode,step);assert.equal(await page.locator('.system-wires>path.active').getAttribute('d'),d.path);assert.equal(await page.locator('.system-wires animateMotion').getAttribute('path'),d.path);assert.deepEqual((await page.locator('.system-node.active').evaluateAll(es=>es.map(e=>e.dataset.role))).sort(),[...new Set([d.from,d.to])].sort());assert.equal(await page.locator('.system-payload').textContent(),d.payload);assert.equal(await page.locator('.parallel-details').evaluate(e=>e.open),false);assert.match(await page.locator('#system-source').getAttribute('href'),new RegExp(M.revision));await geometry(`${width}/${theme}/${mode}/${step}`);if(step<5)await next();}}await choose('topology');assert.equal(await page.locator('#system-controls').isVisible(),false);for(const kind of ['tp','dp','pd']){await page.selectOption('#system-topology',kind);assert.equal(await page.locator('.system-device').count(),2);assert.deepEqual(await page.locator('.system-weight i').evaluateAll(es=>es.map(e=>e.style.width)),Array(6).fill(kind==='tp'?'50%':'100%'));assert.deepEqual(await page.locator('.system-route').allTextContents(),M.topology(kind).assignments.flat());await geometry(`${width}/${theme}/${kind}`);}}}
 await choose('service');await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>!document.querySelector('animateMotion'));assert.equal(await page.locator('animateMotion').count(),0);assert.equal(await page.locator('.system-wires>path.active').count(),1);await page.clock.install();await page.locator('#system-play').click();await page.clock.runFor(2900);assert.equal(await page.locator('#system-scene').getAttribute('data-step'),'1');await page.locator('#system-play').click();await page.clock.runFor(6000);assert.equal(await page.locator('#system-scene').getAttribute('data-step'),'1');await page.locator('#system-next').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#system-scene').getAttribute('data-step'),'2');await page.locator('#system-reset').click();assert.equal(await page.locator('#system-previous').isDisabled(),true);await page.locator('#system-play').click();await page.clock.runFor(15000);assert.equal(await page.locator('#system-play').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('#system-next').isDisabled(),true);
 const plain=await browser.newPage({javaScriptEnabled:false});await plain.goto(base+'sglang/system-overview/');assert.equal(await plain.locator('[data-system-lab]').isVisible(),false);await plain.locator('.topology-detail summary').click();assert.equal(await plain.locator('.system-static').isVisible(),true);await plain.close();assert.deepEqual(errors,[]);console.log('PASS: both causal chains, three deployment scopes, arrow/payload direction, label geometry, four widths × two themes, playback/keyboard, reduced motion, no-JS.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
